function [x_Jdot] = Jdot()
x_Jdot=[[sec(Subscript(\[Theta],1)(t)).^2.*Derivative(1)(Subscript(\[Theta],1))(t),sec( ...
  Subscript(\[Theta],1)(t)).^2.*Derivative(1)(Subscript(r,y))(t) + (-0.258) ...
  .*cos(Subscript(\[Theta],1)(t)).*Derivative(1)(Subscript(\[Theta],1))(t) + ( ...
  -0.04).*sin(Subscript(\[Theta],1)(t)).*Derivative(1)(Subscript(\[Theta],1))(t) + ...
   2.*sec(Subscript(\[Theta],1)(t)).^2.*tan(Subscript(\[Theta],1)(t)).*Subscript( ...
  r,y)(t).*Derivative(1)(Subscript(\[Theta],1))(t),0,0,0,0,0,0;0,0.04.*cos( ...
  Subscript(\[Theta],1)(t)).*Derivative(1)(Subscript(\[Theta],1))(t) + (-0.258).* ...
  sin(Subscript(\[Theta],1)(t)).*Derivative(1)(Subscript(\[Theta],1))(t),0,0,0,0, ...
  0,0;0,0,0,0,0,0,0,0],[sec(Subscript(\[Theta],1)(t)).^2.*Derivative(1)( ...
  Subscript(\[Theta],1))(t),sec(Subscript(\[Theta],1)(t)).^2.*Derivative(1)( ...
  Subscript(r,y))(t) + 0.04.*cos(Subscript(\[Theta],1)(t)).*Derivative(1)( ...
  Subscript(\[Theta],1))(t) + (-0.04).*sin(Subscript(\[Theta],1)(t)).*Derivative( ...
  1)(Subscript(\[Theta],1))(t) + 2.*sec(Subscript(\[Theta],1)(t)).^2.*tan( ...
  Subscript(\[Theta],1)(t)).*Subscript(r,y)(t).*Derivative(1)(Subscript(\[Theta], ...
  1))(t),0,0,0,0,0,0;0,0.04.*cos(Subscript(\[Theta],1)(t)).*Derivative(1)( ...
  Subscript(\[Theta],1))(t) + 0.04.*sin(Subscript(\[Theta],1)(t)).*Derivative(1)( ...
  Subscript(\[Theta],1))(t),0,0,0,0,0,0;0,0,0,0,0,0,0,0]];
